### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by colindean** [slashdotdash/node-ledger-web#13]
On startup:

```
[colin@ayla-wifi node-ledger-web (master)]$ node app.js
util.js:961
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at Object.<anonymous> (/Users/colin/Documents/Finance/node-ledger-web/node_modules/spdy/lib/spdy/connection.js:81:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/colin/Documents/Finance/node-ledger-web/node_modules/spdy/lib/spdy.js:20:19)
```

```
$ node --version
v8.1.3
```

**Comment by colindean** [comment]
Nevermind, this #10
