### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by ArtBIT** [slashdotdash/node-ledger-web#16]
When I try to start the server, I get the following error:
```
util.js:280
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:280:11)
    at Object.<anonymous> (/home/code/nodejs/node-ledger-web/node_modules/spdy/lib/spdy/connection.js:81:6)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/code/nodejs/node-ledger-web/node_modules/spdy/lib/spdy.js:20:19)
```
When I add the following line to the `app.js`
```
process.EventEmitter = require('events').EventEmitter;
```
The server starts but errors out on first page load with the following error:
```
Ledger REST server listening on port 3001
Express server listening on port 3000
RangeError: Maximum call stack size exceeded
    at ServerResponse.get (_http_outgoing.js:113:16)
    at ServerResponse.getHeaders (/home/code/nodejs/node-ledger-web/node_modules/restify/lib/response.js:114:18)
    at ServerResponse.get (_http_outgoing.js:114:17)
    at ServerResponse.getHeaders (/home/code/nodejs/node-ledger-web/node_modules/restify/lib/response.js:114:18)
    at ServerResponse.get (_http_outgoing.js:114:17)
    at ServerResponse.getHeaders (/home/code/nodejs/node-ledger-web/node_modules/restify/lib/response.js:114:18)
    at ServerResponse.get (_http_outgoing.js:114:17)
    at ServerResponse.getHeaders (/home/code/nodejs/node-ledger-web/node_modules/restify/lib/response.js:114:18)
    at ServerResponse.get (_http_outgoing.js:114:17)
    at ServerResponse.getHeaders (/home/code/nodejs/node-ledger-web/node_modules/restify/lib/response.js:114:18)
/home/code/nodejs/node-ledger-web/node_modules/restify/lib/response.js:113
```

**Comment by fifty8** [comment]
Same here

**Comment by kspaans** [comment]
It may be an issue with `restify`, it's been fixed with this PR to `ledger-rest` but not pushed to NPM yet:

https://github.com/slashdotdash/node-ledger-rest/pull/7/files

**Comment by WritwikRay** [comment]
Hey I am getting the same error after 3 years..Is the package dead?
